version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run:
                name: Install Firebase
                command: npm install --save-dev firebase-tools
            - run:
                name: Run Build
                command: npm run build
            - run:
                name: Deploy Master to Firebase
                command: firebase deploy --token=$FIREBASE_TOKEN
workflows:
  build-and-test:
    jobs:
      - build-and-test
